services:

  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"
      - "7001-7099:7001-7099"   # RDS proxy ports
      - "7379-7399:6379-6399"   # ElastiCache proxy ports
    environment:
      SERVICES: "sqs,dynamodb,lambda,iam,logs"
      FLOCI_SERVICES_DOCKER_NETWORK: "getcloudledger"
      FLOCI_SERVICES_RDS_PROXY_BASE_PORT: "7001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    networks:
      - getcloudledger

networks:
  getcloudledger:
    name: getcloudledger
    driver: bridge
