package com.getcloudledger.api.admin.application.rebuild;

import com.getcloudledger.api.shared.domain.bus.command.Command;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.UUID;

/**
 * {@code jobId} is server-generated by the controller before dispatch, so the immediate follow-up
 * {@code GetRebuildJobQuery} can read back the RUNNING row this command creates. {@code accountId}
 * is the single aggregate to replay, or null for a full rebuild of all aggregates.
 */
@Getter
@RequiredArgsConstructor
public class RebuildProjectionsCommand implements Command {
    private final UUID jobId;
    private final UUID accountId;
}
