spring:
  application:
    name: api

  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    schemas: cloudledger

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: cloudledger
    show-sql: false

  cloud:
    aws:
      sqs:
        queue-url: http://localhost:4566/000000000000/cloudledger-events
      region: us-east-1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${COGNITO_JWK_SET_URI:http://localhost:4566/us-east-1_local/.well-known/jwks.json}

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:aws-wrapper:postgresql://localhost:7001/cloudledger
    username: admin
    password: secret123
    driver-class-name: software.amazon.jdbc.Driver

aws:
  dynamodb:
    table-name: cloudledger-projections

management:
  endpoints:
    web:
      exposure:
        include: health
