spring:
  flyway:
    enabled: true

  cloud:
    aws:
      sqs:
        queue-url: ${SQS_QUEUE_URL}
      region: ${AWS_REGION:us-east-1}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: true

  datasource:
    url: jdbc:aws-wrapper:postgresql://${DB_CLUSTER_ENDPOINT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD:}
    hikari:
      data-source-properties:
        wrapperPlugins: failover,efm2
        wrapperDialect: aurora-pg
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException

aws:
  dynamodb:
    table-name: ${DYNAMODB_TABLE_NAME:cloudledger-projections}
